const saaSymboliTaulukko = []

saaSymboliTaulukko[0] = new Image()
saaSymboliTaulukko[0].src = '../symbols/1.svg'
saaSymboliTaulukko[1] = new Image()
saaSymboliTaulukko[1].src = '../symbols/2.svg'
saaSymboliTaulukko[2] = new Image()
saaSymboliTaulukko[2].src = '../symbols/3.svg'
saaSymboliTaulukko[3] = new Image()
saaSymboliTaulukko[3].src = '../symbols/21.svg'
saaSymboliTaulukko[4] = new Image()
saaSymboliTaulukko[4].src = '../symbols/22.svg'
saaSymboliTaulukko[5] = new Image()
saaSymboliTaulukko[5].src = '../symbols/23.svg'
saaSymboliTaulukko[6] = new Image()
saaSymboliTaulukko[6].src = '../symbols/3.svg'
saaSymboliTaulukko[7] = new Image()
saaSymboliTaulukko[7].src = '../symbols/31.svg'
saaSymboliTaulukko[8] = new Image()
saaSymboliTaulukko[8].src = '../symbols/32.svg'
saaSymboliTaulukko[9] = new Image()
saaSymboliTaulukko[9].src = '../symbols/33.svg'
saaSymboliTaulukko[10] = new Image()
saaSymboliTaulukko[10].src = '../symbols/41.svg'
saaSymboliTaulukko[11] = new Image()
saaSymboliTaulukko[11].src = '../symbols/42.svg'
saaSymboliTaulukko[12] = new Image()
saaSymboliTaulukko[12].src = '../symbols/43.svg'
saaSymboliTaulukko[13] = new Image()
saaSymboliTaulukko[13].src = '../symbols/51.svg'
saaSymboliTaulukko[14] = new Image()
saaSymboliTaulukko[14].src = '../symbols/52.svg'
saaSymboliTaulukko[15] = new Image()
saaSymboliTaulukko[15].src = '../symbols/53.svg'
saaSymboliTaulukko[16] = new Image()
saaSymboliTaulukko[16].src = '../symbols/61.svg'
saaSymboliTaulukko[17] = new Image()
saaSymboliTaulukko[17].src = '../symbols/62.svg'
saaSymboliTaulukko[18] = new Image()
saaSymboliTaulukko[18].src = '../symbols/63.svg'
saaSymboliTaulukko[19] = new Image()
saaSymboliTaulukko[19].src = '../symbols/64.svg'
saaSymboliTaulukko[20] = new Image()
saaSymboliTaulukko[20].src = '../symbols/71.svg'
saaSymboliTaulukko[21] = new Image()
saaSymboliTaulukko[21].src = '../symbols/72.svg'
saaSymboliTaulukko[22] = new Image()
saaSymboliTaulukko[22].src = '../symbols/73.svg'
saaSymboliTaulukko[23] = new Image()
saaSymboliTaulukko[23].src = '../symbols/81.svg'
saaSymboliTaulukko[24] = new Image()
saaSymboliTaulukko[24].src = '../symbols/82.svg'
saaSymboliTaulukko[25] = new Image()
saaSymboliTaulukko[25].src = '../symbols/83.svg'
saaSymboliTaulukko[26] = new Image()
saaSymboliTaulukko[26].src = '../symbols/91.svg'
saaSymboliTaulukko[27] = new Image()
saaSymboliTaulukko[27].src = '../symbols/92.svg'


module.exports = saaSymboliTaulukko